### ISSUE TITLE
Get a node graph from TsRoadItem and TsPrefab

### ISSUE THREAD

**Issue by thomasxd24** [dariowouters/ts-map#11]
I am working on a project that calculates the path from a to b and i am looking to create node graph from TsRoadItem and prefabs to run algorithms like Dijkstra. Are there any conections between node and how can i implements this?

Any advice are welcome

**Comment by edoaxyz** [comment]
Check this https://github.com/edoaxyz/ts-map, this is a fork of this project I worked more than one year ago so surely it won't work anymore, but it was able to calculate the path between two prefabs using Dijkstra. You need to consider TsRoadItems as paths and TsPrefabItems as nodes.  Consider that you need to work also with TsPrefab objects because you need to find the right alignment between the node of the prefab and the actual TsRoadItem object. In the fork I've done it by searching the nearest node to the end of the road, but there's an offset value inside .base files that can help you in align the array `nodes` inside TsPrefabItem with the `startnode` or `endnode` of the TsRoadItem object.

**Comment by JAGFx** [comment]
Hi @thomasxd24.

Can you tell me where I can find your project?
I'm planned to work on a feature like this another project.

**Comment by thomasxd24** [comment]
Hi, the project is abandoned, i dont work on the project anymore

**Comment by JAGFx** [comment]
@thomasxd24 I imagine. But can you share me your work ?
