### ISSUE TITLE
Question: How you get the Ets2DlcGuardCount value? 

### ISSUE THREAD

**Issue by JAGFx** [dariowouters/ts-map#20]
Hi,

I'm work on a fork of this project and I need more explanation about this value `Ets2DlcGuardCount`

https://github.com/dariowouters/ts-map/blob/1a77ad3b688cba6359996962b3474f51325834e2/TsMap/TsTypes.cs#L9

Can you tell me how and where you get it?

Thanks ;)

**Comment by meatlayer** [comment]
By the way, this is funny, but I have not changed anything in this value since version 1.38, and ts-map works successfully even with the 1.40 version of games.

```
    public static class Common
    {
        public const int Ets2DlcGuardCount = 10; // TODO: Figure out how to get these dynamically
        public const int AtsDlcGuardCount = 15;
        public const float LaneWidth = 4.5f;
    }

```

**Comment by dariowouters** [comment]
The value is the amount of entries in the `DLC guard` dropdown in the map editor for an item:
![image](https://user-images.githubusercontent.com/5845806/115128742-47248b00-9fe0-11eb-8346-9ad83968ea34.png)

There are items that are in a base game sector but are only used to connect the base map to a DLC area (or a DLC area to another DLC area), and if people don't have that DLC, the game uses that setting to hide certain items so there are no roads that lead to nowhere for those players.

These guards unfortunately seem to only be hardcoded in the game's exe, so I just use a total entry count and don't render anything that has a DLC guard that is higher than the specified value.

Because if you let everything render you can get half finished roads during beta updates like was the case before the Oregon DLC: #4 

Now, the downside with me just using a total number like that is that if you don't have all the DLC then ts-map will render those roads leading to nowhere, as I don't check for specific DLC's being loaded.

<br/>
<br/>

> By the way, this is funny, but I have not changed anything in this value since version 1.38, and ts-map works successfully even with the 1.40 version of games.

If that value is still set at 10 then it will not render the connecting parts between France and Iberia:
![image](https://user-images.githubusercontent.com/5845806/115129425-04fe4800-9fe6-11eb-81b3-a204b0ce3441.png)

**Comment by JAGFx** [comment]
@dariowouters Thanks you so much for you explantation.

I understand how it's work.

If we set a value upper than items count on this list, it's may cause craches and / or mistakes on the map rendering, right ?

**Comment by dariowouters** [comment]
> If we set a value upper than items count on this list, it's may cause craches and / or mistakes on the map rendering, right ?

It shouldn't crash no, what you will get is that there might be some unfinished roads days/weeks before a DLC launches, mostly during an open beta version of the game.


> You know if it's possible to get the DLC areas to get the connected DLC, and then calculate this value dynamically ?

It most likely is possible, but probably not very easily. For me, I don't mind manually updating it as I always check if the DLC works and have to push a commit to update the readme anyway.

**Comment by meatlayer** [comment]
Maybe it's worth considering copy parameters Ets2DlcGuardCount & AtsDlcGuardCount to separate settings through the drop-down menu or through the .ini config file? So that it was not necessary to compile a new exe file for each new DLC.
