### ISSUE TITLE
Import TruckersMP Mods file

### ISSUE THREAD

**Issue by shardick** [dariowouters/ts-map#24]
Hi,

as always, thanks for your great work and dedication.

i know is a strange request but i'm trying to import the TruckersMP Mods Files. 

Looks like the .mp files are loaded correctly and ts-map can look into them but then the modifications should be appplied arent visibile.
Here attached: [mpdata.zip](https://github.com/dariowouters/ts-map/files/8062226/mpdata.zip)

Originally the files are here: C:\ProgramData\TruckersMP\data\ets2\mods 

The game actually load them.

They added a new company and a road from Wroclaw:

![image](https://user-images.githubusercontent.com/518905/153900454-952f9382-331d-44c8-8634-a6a407ed3ffd.png)

Hope you can give me some advice to read them correctly and show on the map.

Thanks

**Comment by dariowouters** [comment]
Unfortunately the way I implemented the SCS filesystem in this project is it looks for directories in the SCS files and then reads their contents.

TruckersMP on the other hand creates their SCS (*.mp) files with the minimum amount of directories possible (to make it harder to extract I presume).

So they don't really work well in this program without changing how the filesystem works. So in the meantime I extracted the map and overlay from the MP file and included it here: [hq_stage_out.zip](https://github.com/dariowouters/ts-map/files/8063712/hq_stage_out.zip).
You can use that file instead of the MP one to generate the map.

**Comment by shardick** [comment]
Can i ask how you extracted it?

**Comment by shardick** [comment]
that's neat.

do you have a PayPal.me? i would to do a donation for your amazing work

**Comment by dariowouters** [comment]
Sure: https://paypal.me/dariowouters

Much appreciated but definitely not required to do so.

**Comment by shardick** [comment]
thanks!

**Comment by shardick** [comment]
Priceless!
Thanks!!!!

![Uploading image.png…]()

**Comment by shardick** [comment]
Thanks! Priceeless! unfortunately my fork is ahead of many modifications i did on my side, will try to merge
